#!/bin/bash
#
# Run SPECFEM2D on the Marmousi case generated by build_specfem_case.py.
# Set SPECFEM_ROOT to your SPECFEM2D installation.
#
set -e

SPECFEM_ROOT=${SPECFEM_ROOT:-/home/mtran/specfem2d}

echo "running: $(date)"

mkdir -p OUTPUT_FILES bin
rm -rf OUTPUT_FILES/*

ln -sf "$SPECFEM_ROOT/bin/xmeshfem2D" bin/xmeshfem2D
ln -sf "$SPECFEM_ROOT/bin/xspecfem2D" bin/xspecfem2D

cp DATA/Par_file DATA/SOURCE DATA/STATIONS OUTPUT_FILES/

NPROC=$(grep ^NPROC DATA/Par_file | cut -d = -f 2 | cut -d \# -f 1 | tr -d ' ')

run() {
  if [ "$NPROC" -eq 1 ]; then "$1"; else mpirun -np "$NPROC" "$1"; fi
}

echo "running mesher on $NPROC core(s)..."
run ./bin/xmeshfem2D

echo "running solver on $NPROC core(s)..."
run ./bin/xspecfem2D

echo "done: $(date) - seismograms in OUTPUT_FILES/"
